- pkg:cargo/dependabot-config@0.1.0
- pkg:cargo/dependabot-config@0.2.0
- pkg:cargo/dependabot-config@0.2.1
- pkg:cargo/dependabot-config@0.2.2
- pkg:cargo/dependabot-config@0.3.0
- pkg:cargo/dependabot-config@0.3.1
- pkg:cargo/dependabot-config@0.3.2
- pkg:cargo/dependabot-config@0.3.3
- pkg:cargo/dependabot-config@0.3.4
